#ifndef __ENUMS_H__
#define __ENUMS_H__


enum Tokens{
   ACCESSOR,
   SECTION,
   DIRECTIVE,
   LABEL,
   OPCODE,
   REG_IMM_DEC_OPERAND,
   REG_IMM_HEX_OPERAND,
   REG_SYM_OPERAND,
   REG_REG_OPERAND,
   REG_REG_IND_OPERAND,
   REG_REGINDIMM_DEC_OPERAND,
   REG_REGINDIMM_HEX_OPERAND,
   REG_REGINDSYM_OPERAND,
   REG_MEMDIR_DEC_OPERAND,
   REG_MEMDIR_HEX_OPERAND,
   REG_MEMDIR_SYM_OPERAND,
   JMP_IMM_DEC_OPERAND,
   JMP_IMM_HEX_OPERAND,
   JMP_SYM_OPERAND,
   JMP_REG_OPERAND,
   JMP_REG_IND_OPERAND,
   JMP_REGINDIMM_DEC_OPERAND,
   JMP_REGINDIMM_HEX_OPERAND,
   JMP_REGINDSYM_OPERAND,
   JMP_MEMDIR_DEC_OPERAND,
   JMP_MEMDIR_HEX_OPERAND,
   JMP_MEMDIR_SYM_OPERAND

};

enum Opcodes{
    HALT=0,
    IRET=1,
    RET=2,
    INT=3,
    CALL=4,
    JMP=5,
    JEQ=6,
    JNE=7,
    JGT=8,
    PUSH=9,
    POP=10,
    XCHG=11,
    MOV=12,
    ADD=13,
    SUB=14,
    MUL=15,
    DIV=16,
    CMP=17,
    NOT=18,
    AND=19,
    OR=20,
    XOR=21,
    TEST=22,
    SHL=23,
    SHR=24
};

#endif
